### ISSUE TITLE
Chyba importu popisnych informacii

### ISSUE THREAD

**Issue by mmunko** [imincik/kataster-import#1]
Nie je mozne importovat subor popisnych informacii, 
v tabulkach:
kn_lv  -- chybaju stlpce slv a dst
kn_vl -- chyba stlpec pcz

Pripajam aj testovacie data, na ktorych som skusil vykonat import KN
[import-kn.zip](https://github.com/imincik/kataster-import/files/65863/import-kn.zip)

**Comment by stanom** [comment]
Ano, navrh zmeny vid -> https://github.com/stanom/kataster-import/commit/b32100a6c660e3d23c99d5f5a106af5ad4ac9f05?diff=unified

**Comment by imincik** [comment]
Fixed in cb0202074538b2674ea7c5279934dd8345b5432e
